### ISSUE TITLE
Add sign a transaction to the Wrapper

### ISSUE THREAD

**Issue by wantedsystem** [Consensys/get-starknet#6]
starkNet_signTransaction method

**Comment by Subbitoooo** [comment]
Hello sir, I'm very happy to help you for this issues. If you want to  sign a transaction in StarkNet, gather transaction details, use a StarkNet-compatible wallet (e.g., MetaMask), connect to the StarkNet network, initiate the transaction, sign when prompted, and wait for confirmation. Hope that This will help you. Have a nice day ;)
